### ISSUE TITLE
N-dimensional pretty printing

### ISSUE THREAD

**Issue by mikera** [mikera/core.matrix#43]
Follow on from https://github.com/mikera/matrix-api/issues/15

Pretty-printing of different (non-2D) array sizes currently fails with errors like:

```
java.lang.UnsupportedOperationException: nth not supported on this type:      ScalarWrapper
    at clojure.lang.RT.nthFrom(RT.java:846) 
    at clojure.lang.RT.nth(RT.java:796)
    at clojure.core.matrix$pm.invoke(matrix.clj:999)
```

`pm` needs extending to handle these cases

**Comment by mars0i** [comment]
Pretty-printing of matrices with more than two rows is odd:

``` clojure
=> (pm (matrix :ndarray [1 2 3]))
[1.000 2.000 3.000]
nil
=> (pm (matrix :ndarray [[1 2 3][4 5 6]]))
[[1.000 2.000 3.000]
 [4.000 5.000 6.000]]
nil
=> (pm (matrix :ndarray [[1 2 3][4 5 6][7 8 9]]))
[[1.000 2.000 3.000]

 [4.000 5.000 6.000] [7.000 8.000 9.000]]
nil
=> (pm (matrix :ndarray [[1 2 3][4 5 6][7 8 9][10 11 12]]))
[[ 1.000  2.000  3.000]


 [ 4.000  5.000  6.000] [ 7.000  8.000  9.000] [10.000 11.000 12.000]]
nil
=> (pm (matrix :persistent-vector [[1 2 3][4 5 6][7 8 9][10 11 12]]))
[[ 1.000  2.000  3.000]


 [ 4.000  5.000  6.000] [ 7.000  8.000  9.000] [10.000 11.000 12.000]]
nil
=> (pm (matrix :clatrix [[1 2 3][4 5 6][7 8 9][10 11 12]]))
[[ 1.000  2.000  3.000]


 [ 4.000  5.000  6.000] [ 7.000  8.000  9.000] [10.000 11.000 12.000]]
nil
```

**Comment by mikera** [comment]
Yeah the `pm` stuff pretty much needs a complete rewrite......

**Comment by mars0i** [comment]
I had written some of my own pretty-printing functions before I discovered `pm`.  Maybe I will look at it at some point when I have a chance.

**Comment by mikera** [comment]
OK cool. I've fixed this immediate issue but if you feel like improving pprint generally then any contributions would be much appreciated!
